name = "ekubo-api"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[placement]
mode = "smart"

[limits]
cpu_ms = 5000

[vars]
# only used for running the api locally
PG_CONNECTION_STRING = "postgresql://postgres:postgres@localhost:5432/postgres"
ZERO_X_API_KEY = "9bdd43e7-e8bd-4a54-b9e0-64340c1eb681"

[env.prod]
hyperdrive = [
    { binding = "HYPERDRIVE", id = "04a121d0804b4451b6cdf894c9b61b56" },
]
routes = [{ pattern = "prod-api.ekubo.org", custom_domain = true }]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
