name = "evm-api"
main = "src/index.ts"
compatibility_date = "2023-03-14"
node_compat = true

[placement]
mode = "smart"

[limits]
cpu_ms = 5000

[vars]
CHAIN_ID = "11155111"
# only used for running the api locally
PG_CONNECTION_STRING = "postgresql://postgres:postgres@localhost:5432/evm_sepolia"

[env.sepolia]
hyperdrive = [
    { binding = "HYPERDRIVE", id = "48dd80eff90249868cc5a1ee4b966ac5" }
]
vars = { CHAIN_ID = "11155111" }

[env.mainnet]
hyperdrive = [
    { binding = "HYPERDRIVE", id = "40ad51ac50dd4f29a332f750e6dd7110" }
]
vars = { CHAIN_ID = "1" }

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.