name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:


concurrency: deploy

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - network_name: mainnet
            secret_name: PG_CONNECTION_STRING_MAINNET
          - network_name: goerli
            secret_name: PG_CONNECTION_STRING_GOERLI

    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: |
            deploy --env ${{ matrix.network_name }} --var PG_CONNECTION_STRING:${{ secrets[matrix.secret_name] }}