name: Deploy

on:
  push:
    branches:
      - main

concurrency: deploy-cf

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - deploy_env: prod

    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            deploy --env ${{ matrix.deploy_env }} --minify
