name: Deploy

on:
  push:
    branches:
      - main

concurrency: deploy-cf

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - deploy_env: prod

    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun ci

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            deploy --env ${{ matrix.deploy_env }} --minify
